security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    role_hierarchy:
        ROLE_ADMIN: [ROLE_DIRECTION, ROLE_COMMERCIAL, ROLE_ACHAT, ROLE_LOGISTIQUE, ROLE_USER]

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator
            entry_point: App\Security\LoginFormAuthenticator
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/parametrage, roles: [ROLE_ADMIN] }
        - { path: ^/utilisateurs, roles: [ROLE_ADMIN] }
        - { path: ^/dashboard, roles: [ROLE_ADMIN, ROLE_DIRECTION] }
        - { path: ^/parametres/choix, roles: [ROLE_ADMIN] }
        - { path: ^/marches, roles: [ROLE_ADMIN, ROLE_DIRECTION] }
        - { path: ^/objectifs, roles: [ROLE_ADMIN, ROLE_DIRECTION] }
        - { path: ^/zones, roles: [ROLE_ADMIN, ROLE_DIRECTION] }
        - { path: ^/commerciaux, roles: [ROLE_ADMIN, ROLE_DIRECTION] }
        - { path: ^/clients, roles: [ROLE_ADMIN, ROLE_DIRECTION] }
        - { path: ^/visites/[0-9]+/outcome$, roles: [ROLE_ADMIN, ROLE_DIRECTION, ROLE_COMMERCIAL] }
        - { path: ^/visites, roles: [ROLE_ADMIN, ROLE_DIRECTION] }
        - { path: ^/tournees, roles: [ROLE_ADMIN, ROLE_DIRECTION, ROLE_COMMERCIAL] }
        - { path: ^/offres, roles: [ROLE_ADMIN, ROLE_DIRECTION] }
        - { path: ^/fournisseurs, roles: [ROLE_ADMIN, ROLE_ACHAT] }
        - { path: ^/consultations-fournisseurs, roles: [ROLE_ADMIN, ROLE_ACHAT] }
        - { path: ^/imports, roles: [ROLE_ADMIN, ROLE_ACHAT] }
        - { path: ^/produits, roles: [ROLE_ADMIN, ROLE_ACHAT, ROLE_LOGISTIQUE] }
        - { path: ^/lancements-produits, roles: [ROLE_ADMIN, ROLE_DIRECTION, ROLE_ACHAT] }
        - { path: ^/livraisons, roles: [ROLE_ADMIN, ROLE_LOGISTIQUE] }
        - { path: ^/retours-terrain, roles: [ROLE_ADMIN, ROLE_DIRECTION, ROLE_COMMERCIAL] }
        - { path: ^/reunions-commerciales, roles: [ROLE_ADMIN, ROLE_DIRECTION] }
        - { path: ^/satisfaction-clients, roles: [ROLE_ADMIN, ROLE_DIRECTION, ROLE_COMMERCIAL] }
        - { path: ^/, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
